name: Mirror to readonly
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Push to readonly branch
        run: |
          git config --global user.name 'Mirror action'
          git config --global user.email 'your-username@users.noreply.github.com'
          git push origin main:readonly
